// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MinGo.MyBillBook.Data;

#nullable disable

namespace MinGo.MyBillBook.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260922042814_Phase5TagSystem")]
    partial class Phase5TagSystem
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("MinGo.MyBillBook.Core.Models.BillCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ParentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("BillCategories");
                });

            modelBuilder.Entity("MinGo.MyBillBook.Core.Models.BillImportBatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DuplicateCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ImportDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("PlatformId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SuccessCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PlatformId");

                    b.ToTable("BillImportBatches");
                });

            modelBuilder.Entity("MinGo.MyBillBook.Core.Models.BillRawRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("DuplicateScore")
                        .HasColumnType("REAL");

                    b.Property<int>("DuplicateStatus")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ImportBatchId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsProcessed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlatformId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RawPayload")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RowNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceTransactionId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ImportBatchId");

                    b.HasIndex("PlatformId");

                    b.HasIndex("SourceTransactionId");

                    b.ToTable("BillRawRecords");
                });

            modelBuilder.Entity("MinGo.MyBillBook.Core.Models.BillRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("AmountMinor")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Counterparty")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int?>("FundAccountId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsManualAdjusted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Merchant")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int?>("MerchantId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlatformId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("RawRecordId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceFile")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("SyncedToDuckDb")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("TransactionType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("FundAccountId");

                    b.HasIndex("MerchantId");

                    b.HasIndex("PlatformId");

                    b.HasIndex("RawRecordId");

                    b.HasIndex("SyncedToDuckDb");

                    b.HasIndex("TransactionDate");

                    b.ToTable("BillRecords");
                });

            modelBuilder.Entity("MinGo.MyBillBook.Core.Models.CategoryRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MatchField")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MatchPattern")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Priority");

                    b.ToTable("CategoryRules");
                });

            modelBuilder.Entity("MinGo.MyBillBook.Core.Models.CategoryTag", b =>
                {
                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TagId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CategoryId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("CategoryTags");
                });

            modelBuilder.Entity("MinGo.MyBillBook.Core.Models.ClassificationResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Confidence")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Field")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RuleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Source")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TransactionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TransactionId");

                    b.HasIndex("TransactionId", "Field");

                    b.ToTable("ClassificationResults");
                });

            modelBuilder.Entity("MinGo.MyBillBook.Core.Models.DuplicateCandidate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("LeftRecordId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MatchReason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("RightRecordId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Score")
                        .HasColumnType("REAL");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LeftRecordId");

                    b.HasIndex("RightRecordId");

                    b.HasIndex("Status");

                    b.ToTable("DuplicateCandidates");
                });

            modelBuilder.Entity("MinGo.MyBillBook.Core.Models.FundAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccountType")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Balance")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("PlatformId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PlatformId");

                    b.ToTable("FundAccounts");
                });

            modelBuilder.Entity("MinGo.MyBillBook.Core.Models.Merchant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CanonicalName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CanonicalName")
                        .IsUnique();

                    b.ToTable("Merchants");
                });

            modelBuilder.Entity("MinGo.MyBillBook.Core.Models.MerchantAlias", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MatchType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MerchantId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Pattern")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MerchantId");

                    b.HasIndex("Priority");

                    b.ToTable("MerchantAliases");
                });

            modelBuilder.Entity("MinGo.MyBillBook.Core.Models.NormalizedTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("AmountMinor")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Counterparty")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<double>("DuplicateScore")
                        .HasColumnType("REAL");

                    b.Property<int>("DuplicateStatus")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("RawDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("RawRecordId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceTransactionId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAt");

                    b.HasIndex("RawRecordId");

                    b.ToTable("NormalizedTransactions");
                });

            modelBuilder.Entity("MinGo.MyBillBook.Core.Models.PaymentPlatform", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("IconUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("PaymentPlatforms");
                });

            modelBuilder.Entity("MinGo.MyBillBook.Core.Models.PipelineRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ImportBatchId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PipelineType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ImportBatchId");

                    b.HasIndex("Status");

                    b.ToTable("PipelineRuns");
                });

            modelBuilder.Entity("MinGo.MyBillBook.Core.Models.PipelineStepRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ErrorCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InputCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OutputCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PipelineRunId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StepName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("WarningCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PipelineRunId");

                    b.ToTable("PipelineStepRuns");
                });

            modelBuilder.Entity("MinGo.MyBillBook.Core.Models.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("Scope")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ScopeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TagType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("TagType");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("MinGo.MyBillBook.Core.Models.TagRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Condition")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConditionValue")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TagId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Priority");

                    b.HasIndex("TagId");

                    b.ToTable("TagRules");
                });

            modelBuilder.Entity("MinGo.MyBillBook.Core.Models.TransactionTag", b =>
                {
                    b.Property<int>("TransactionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TagId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Confidence")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Source")
                        .HasColumnType("INTEGER");

                    b.HasKey("TransactionId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("TransactionTags");
                });

            modelBuilder.Entity("MinGo.MyBillBook.Core.Models.BillCategory", b =>
                {
                    b.HasOne("MinGo.MyBillBook.Core.Models.BillCategory", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("MinGo.MyBillBook.Core.Models.BillImportBatch", b =>
                {
                    b.HasOne("MinGo.MyBillBook.Core.Models.PaymentPlatform", "Platform")
                        .WithMany()
                        .HasForeignKey("PlatformId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Platform");
                });

            modelBuilder.Entity("MinGo.MyBillBook.Core.Models.BillRawRecord", b =>
                {
                    b.HasOne("MinGo.MyBillBook.Core.Models.BillImportBatch", "ImportBatch")
                        .WithMany("RawRecords")
                        .HasForeignKey("ImportBatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MinGo.MyBillBook.Core.Models.PaymentPlatform", "Platform")
                        .WithMany()
                        .HasForeignKey("PlatformId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ImportBatch");

                    b.Navigation("Platform");
                });

            modelBuilder.Entity("MinGo.MyBillBook.Core.Models.BillRecord", b =>
                {
                    b.HasOne("MinGo.MyBillBook.Core.Models.BillCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId");

                    b.HasOne("MinGo.MyBillBook.Core.Models.FundAccount", "FundAccount")
                        .WithMany()
                        .HasForeignKey("FundAccountId");

                    b.HasOne("MinGo.MyBillBook.Core.Models.Merchant", "MerchantRef")
                        .WithMany("BillRecords")
                        .HasForeignKey("MerchantId");

                    b.HasOne("MinGo.MyBillBook.Core.Models.PaymentPlatform", "Platform")
                        .WithMany()
                        .HasForeignKey("PlatformId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MinGo.MyBillBook.Core.Models.BillRawRecord", "RawRecord")
                        .WithMany()
                        .HasForeignKey("RawRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("FundAccount");

                    b.Navigation("MerchantRef");

                    b.Navigation("Platform");

                    b.Navigation("RawRecord");
                });

            modelBuilder.Entity("MinGo.MyBillBook.Core.Models.CategoryRule", b =>
                {
                    b.HasOne("MinGo.MyBillBook.Core.Models.BillCategory", "Category")
                        .WithMany("Rules")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("MinGo.MyBillBook.Core.Models.CategoryTag", b =>
                {
                    b.HasOne("MinGo.MyBillBook.Core.Models.BillCategory", "Category")
                        .WithMany("CategoryTags")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MinGo.MyBillBook.Core.Models.Tag", "Tag")
                        .WithMany("CategoryTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("MinGo.MyBillBook.Core.Models.ClassificationResult", b =>
                {
                    b.HasOne("MinGo.MyBillBook.Core.Models.BillRecord", "Transaction")
                        .WithMany("ClassificationResults")
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("MinGo.MyBillBook.Core.Models.DuplicateCandidate", b =>
                {
                    b.HasOne("MinGo.MyBillBook.Core.Models.BillRecord", "LeftRecord")
                        .WithMany()
                        .HasForeignKey("LeftRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MinGo.MyBillBook.Core.Models.BillRecord", "RightRecord")
                        .WithMany()
                        .HasForeignKey("RightRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LeftRecord");

                    b.Navigation("RightRecord");
                });

            modelBuilder.Entity("MinGo.MyBillBook.Core.Models.FundAccount", b =>
                {
                    b.HasOne("MinGo.MyBillBook.Core.Models.PaymentPlatform", "Platform")
                        .WithMany("FundAccounts")
                        .HasForeignKey("PlatformId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Platform");
                });

            modelBuilder.Entity("MinGo.MyBillBook.Core.Models.MerchantAlias", b =>
                {
                    b.HasOne("MinGo.MyBillBook.Core.Models.Merchant", "Merchant")
                        .WithMany("Aliases")
                        .HasForeignKey("MerchantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Merchant");
                });

            modelBuilder.Entity("MinGo.MyBillBook.Core.Models.NormalizedTransaction", b =>
                {
                    b.HasOne("MinGo.MyBillBook.Core.Models.BillRawRecord", "RawRecord")
                        .WithMany()
                        .HasForeignKey("RawRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RawRecord");
                });

            modelBuilder.Entity("MinGo.MyBillBook.Core.Models.PipelineRun", b =>
                {
                    b.HasOne("MinGo.MyBillBook.Core.Models.BillImportBatch", "ImportBatch")
                        .WithMany()
                        .HasForeignKey("ImportBatchId");

                    b.Navigation("ImportBatch");
                });

            modelBuilder.Entity("MinGo.MyBillBook.Core.Models.PipelineStepRun", b =>
                {
                    b.HasOne("MinGo.MyBillBook.Core.Models.PipelineRun", "Run")
                        .WithMany("Steps")
                        .HasForeignKey("PipelineRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Run");
                });

            modelBuilder.Entity("MinGo.MyBillBook.Core.Models.TagRule", b =>
                {
                    b.HasOne("MinGo.MyBillBook.Core.Models.Tag", "Tag")
                        .WithMany("Rules")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("MinGo.MyBillBook.Core.Models.TransactionTag", b =>
                {
                    b.HasOne("MinGo.MyBillBook.Core.Models.Tag", "Tag")
                        .WithMany("TransactionTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MinGo.MyBillBook.Core.Models.BillRecord", "Transaction")
                        .WithMany("Tags")
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tag");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("MinGo.MyBillBook.Core.Models.BillCategory", b =>
                {
                    b.Navigation("CategoryTags");

                    b.Navigation("Children");

                    b.Navigation("Rules");
                });

            modelBuilder.Entity("MinGo.MyBillBook.Core.Models.BillImportBatch", b =>
                {
                    b.Navigation("RawRecords");
                });

            modelBuilder.Entity("MinGo.MyBillBook.Core.Models.BillRecord", b =>
                {
                    b.Navigation("ClassificationResults");

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("MinGo.MyBillBook.Core.Models.Merchant", b =>
                {
                    b.Navigation("Aliases");

                    b.Navigation("BillRecords");
                });

            modelBuilder.Entity("MinGo.MyBillBook.Core.Models.PaymentPlatform", b =>
                {
                    b.Navigation("FundAccounts");
                });

            modelBuilder.Entity("MinGo.MyBillBook.Core.Models.PipelineRun", b =>
                {
                    b.Navigation("Steps");
                });

            modelBuilder.Entity("MinGo.MyBillBook.Core.Models.Tag", b =>
                {
                    b.Navigation("CategoryTags");

                    b.Navigation("Rules");

                    b.Navigation("TransactionTags");
                });
#pragma warning restore 612, 618
        }
    }
}
