// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MinGo.MyBillBook.Data;

#nullable disable

namespace MinGo.MyBillBook.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260922031046_AddPipelineTracking")]
    partial class AddPipelineTracking
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("MinGo.MyBillBook.Core.Models.BillCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ParentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("BillCategories");
                });

            modelBuilder.Entity("MinGo.MyBillBook.Core.Models.BillImportBatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DuplicateCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ImportDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("PlatformId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SuccessCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PlatformId");

                    b.ToTable("BillImportBatches");
                });

            modelBuilder.Entity("MinGo.MyBillBook.Core.Models.BillRawRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<string>("Counterparty")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ImportBatchId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsProcessed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PlatformId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RawData")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("TransactionId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ImportBatchId");

                    b.HasIndex("PlatformId");

                    b.HasIndex("TransactionId");

                    b.ToTable("BillRawRecords");
                });

            modelBuilder.Entity("MinGo.MyBillBook.Core.Models.BillRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Counterparty")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int?>("FundAccountId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsManualAdjusted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Merchant")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("PlatformId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("RawRecordId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceFile")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("SyncedToDuckDb")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("TransactionType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("FundAccountId");

                    b.HasIndex("PlatformId");

                    b.HasIndex("RawRecordId");

                    b.HasIndex("SyncedToDuckDb");

                    b.HasIndex("TransactionDate");

                    b.ToTable("BillRecords");
                });

            modelBuilder.Entity("MinGo.MyBillBook.Core.Models.CategoryRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MatchField")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MatchPattern")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Priority");

                    b.ToTable("CategoryRules");
                });

            modelBuilder.Entity("MinGo.MyBillBook.Core.Models.FundAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccountType")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Balance")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("PlatformId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PlatformId");

                    b.ToTable("FundAccounts");
                });

            modelBuilder.Entity("MinGo.MyBillBook.Core.Models.PaymentPlatform", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("IconUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("PaymentPlatforms");
                });

            modelBuilder.Entity("MinGo.MyBillBook.Core.Models.PipelineRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ImportBatchId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PipelineType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ImportBatchId");

                    b.HasIndex("Status");

                    b.ToTable("PipelineRuns");
                });

            modelBuilder.Entity("MinGo.MyBillBook.Core.Models.PipelineStepRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ErrorCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InputCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OutputCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PipelineRunId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StepName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("WarningCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PipelineRunId");

                    b.ToTable("PipelineStepRuns");
                });

            modelBuilder.Entity("MinGo.MyBillBook.Core.Models.BillCategory", b =>
                {
                    b.HasOne("MinGo.MyBillBook.Core.Models.BillCategory", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("MinGo.MyBillBook.Core.Models.BillImportBatch", b =>
                {
                    b.HasOne("MinGo.MyBillBook.Core.Models.PaymentPlatform", "Platform")
                        .WithMany()
                        .HasForeignKey("PlatformId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Platform");
                });

            modelBuilder.Entity("MinGo.MyBillBook.Core.Models.BillRawRecord", b =>
                {
                    b.HasOne("MinGo.MyBillBook.Core.Models.BillImportBatch", "ImportBatch")
                        .WithMany("RawRecords")
                        .HasForeignKey("ImportBatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MinGo.MyBillBook.Core.Models.PaymentPlatform", "Platform")
                        .WithMany()
                        .HasForeignKey("PlatformId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ImportBatch");

                    b.Navigation("Platform");
                });

            modelBuilder.Entity("MinGo.MyBillBook.Core.Models.BillRecord", b =>
                {
                    b.HasOne("MinGo.MyBillBook.Core.Models.BillCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId");

                    b.HasOne("MinGo.MyBillBook.Core.Models.FundAccount", "FundAccount")
                        .WithMany()
                        .HasForeignKey("FundAccountId");

                    b.HasOne("MinGo.MyBillBook.Core.Models.PaymentPlatform", "Platform")
                        .WithMany()
                        .HasForeignKey("PlatformId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MinGo.MyBillBook.Core.Models.BillRawRecord", "RawRecord")
                        .WithMany()
                        .HasForeignKey("RawRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("FundAccount");

                    b.Navigation("Platform");

                    b.Navigation("RawRecord");
                });

            modelBuilder.Entity("MinGo.MyBillBook.Core.Models.CategoryRule", b =>
                {
                    b.HasOne("MinGo.MyBillBook.Core.Models.BillCategory", "Category")
                        .WithMany("Rules")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("MinGo.MyBillBook.Core.Models.FundAccount", b =>
                {
                    b.HasOne("MinGo.MyBillBook.Core.Models.PaymentPlatform", "Platform")
                        .WithMany("FundAccounts")
                        .HasForeignKey("PlatformId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Platform");
                });

            modelBuilder.Entity("MinGo.MyBillBook.Core.Models.PipelineRun", b =>
                {
                    b.HasOne("MinGo.MyBillBook.Core.Models.BillImportBatch", "ImportBatch")
                        .WithMany()
                        .HasForeignKey("ImportBatchId");

                    b.Navigation("ImportBatch");
                });

            modelBuilder.Entity("MinGo.MyBillBook.Core.Models.PipelineStepRun", b =>
                {
                    b.HasOne("MinGo.MyBillBook.Core.Models.PipelineRun", "Run")
                        .WithMany("Steps")
                        .HasForeignKey("PipelineRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Run");
                });

            modelBuilder.Entity("MinGo.MyBillBook.Core.Models.BillCategory", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Rules");
                });

            modelBuilder.Entity("MinGo.MyBillBook.Core.Models.BillImportBatch", b =>
                {
                    b.Navigation("RawRecords");
                });

            modelBuilder.Entity("MinGo.MyBillBook.Core.Models.PaymentPlatform", b =>
                {
                    b.Navigation("FundAccounts");
                });

            modelBuilder.Entity("MinGo.MyBillBook.Core.Models.PipelineRun", b =>
                {
                    b.Navigation("Steps");
                });
#pragma warning restore 612, 618
        }
    }
}
